Add dotenv
kekkorider/nuxt-prismic-app pull request #1
Opened 2019-06-03 04:04 UTC by Jack-Barry

Hey amigo,

I really appreciated your tutorial. I did run into some issues though, and created this pull request in the hopes that others trying to build similar projects won't have some of the same troubles.

What was performed:

* Fixed some typos that resulted in faulty building and generating (these should definitely be fixed in the tutorial code, if nothing else)
* Added the ability to use `.env` file during development to keep secret keys more secure
* Threw in some `async` functions to make things easier to follow

What changes for the developer:

* You can set environment variables via command line or in the admin panel of tools like Netlify (no more API keys in code! 🙌🏻)
* The `generate` and `build` commands *do* require setting `PRISMIC_API_URL` and `PRISMIC_API_KEY` since they are production builds. You can use a `.env` file when running in development mode though.

Let me know if this all makes sense, once again thanks for getting me on the right path to figure out this Nuxt thing!

Cheers 🍺

2019-06-05 15:47 UTC, kekkorider commented
Hey @Jack-Barry, happy that my tutorial helped you!

Also, thank you for this PR, everything seems more than good; I will take a better look in the next days and get back to you.

Cheers!

2019-06-06 03:13 UTC, Jack-Barry commented
🤦🏻‍♂️I just noticed a few issues when I deployed to Netlify with my personal project - will update this request when I get the code updated for it!

2019-06-07 02:48 UTC, Jack-Barry commented
Without that last commit the pages would load on my Netlify deployment, but required refresh. It's all good now 👍🏼

2019-06-14 10:54 UTC, kekkorider requested changes
@Jack-Barry again, thanks a lot 🙏 

There are a couple of imports that should be removed since they're not needed anymore.

~Aso, I'm getting an error while running `nuxt generate` on my local machine (everything works fine when in development):~

EDIT: Never mind, I forgot to add `PRISMIC_API_URL ` and `PRISMIC_API_KEY` to the `generate` command.

![Schermata 2019-06-14 alle 12 36 45](https://user-images.githubusercontent.com/5191941/59504509-65c91080-8ea3-11e9-99b8-5342a7dc035b.png)

2019-06-14 10:54 UTC, kekkorider commented on nuxt.config.js
> +const Prismic = require("prismic-javascript");
This is not needed anymore.

2019-06-14 10:54 UTC, kekkorider commented on nuxt.config.js
> +import { initApi, queryForDocType } from "./prismic.config";
`initAPI` is not needed anymore.

2019-06-14 10:54 UTC, kekkorider commented on pages/about.vue
>  import Prismic from 'prismic-javascript'
This can be removed, it's not needed anymore.

2019-06-14 10:54 UTC, kekkorider commented on pages/blog/index.vue
>  import Prismic from 'prismic-javascript'
This can be removed, it's not needed anymore.

2019-06-14 10:54 UTC, kekkorider commented on pages/index.vue
>  import Prismic from 'prismic-javascript'
This can be removed, it's not needed anymore.

2022-03-20 21:49 UTC, closed without merging